os: Visual Studio 2015
version: 1.2.1.{build}
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  # C:\projects\eventbus
  - echo %CD%
  # C:\projects\eventbus\EventBus
  - ps: cd src
  - echo %CD%
  - git --version
  - git rev-list --count HEAD

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: '{version}'

before_build:
  - cmd: nuget restore RazorTemplates.sln
build_script:
  - echo %CD%
  #- msbuild RazorTemplates.sln
  - msbuild RazorTemplates.Core\RazorTemplates.Core.csproj /t:Rebuild /p:Platform=AnyCPU /p:Configuration=Release
  - msbuild RazorTemplates.Samples\RazorTemplates.Samples.csproj /t:Rebuild /p:Platform=AnyCPU /p:Configuration=Release
  - msbuild RazorTemplates.Tests\RazorTemplates.Tests.csproj /t:Rebuild /p:Platform=AnyCPU /p:Configuration=Release /p:DefineConstants=CI
